--
-- PostgreSQL database dump
--

-- Dumped from database version 12.4
-- Dumped by pg_dump version 16.3

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: postgres
--

-- *not* creating schema, since initdb creates it


ALTER SCHEMA public OWNER TO postgres;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: organizations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.organizations (
    id bigint NOT NULL,
    created_by bigint,
    name character varying(255)
);


ALTER TABLE public.organizations OWNER TO postgres;

--
-- Name: organizations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.organizations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.organizations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    email_id character varying(255) NOT NULL,
    name character varying(255),
    password character varying(255),
    role character varying(255),
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone
);


ALTER TABLE public.users OWNER TO postgres;

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: organizations; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.organizations (id, created_by, name) FROM stdin;
5	1	Org Test
6	4	Org Tust
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users (id, email_id, name, password, role, created_at, updated_at) FROM stdin;
3	test@gmail.com	Test	$2a$10$pAOQSrG4tG4GFDkneP1G4eAVVIR5RjmyGLeMbJn1IGCix3JwG/.4e	superadmin	2024-07-29 15:53:40.156	2024-07-29 15:53:40.156
1	admin@gmail.com	Super Admin	$2a$10$vBW4PdODBVn/RHOQd7cQo.C9H3c4F1/ETommkicAk87VtSUBxnSt.	superadmin	\N	2024-07-29 15:58:11.177
4	user@gmail.com	User	$2a$10$iq3P/ZAuVRtbRF1kvNeSf.X5vJNPGnNdn8pLi3hKjFSk/inLqYUk6	user	2024-07-29 16:44:02.472	2024-07-29 16:44:02.472
5	user1@gmail.com	User1	$2a$10$EWgCopDSQD92iSysTsgsBuNVqMF8X7/HH2OYz.2OtbPEQGjGyIgVC	user	2024-07-29 19:22:12.047	2024-07-29 19:22:12.047
6	ritjobportal@gmail.com	User 2	$2a$10$J99S3PdW3yrlWL6VX4InsO09C8XskPKPeTG.GOl6gQlCDijvjRUvy	user	2024-07-29 19:22:51.677	2024-07-29 19:22:51.677
\.


--
-- Name: organizations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.organizations_id_seq', 6, true);


--
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_id_seq', 6, true);


--
-- Name: organizations organizations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.organizations
    ADD CONSTRAINT organizations_pkey PRIMARY KEY (id);


--
-- Name: users ukpwrpg821nujmmnavoq7s420jn; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT ukpwrpg821nujmmnavoq7s420jn UNIQUE (email_id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: postgres
--

REVOKE USAGE ON SCHEMA public FROM PUBLIC;
GRANT ALL ON SCHEMA public TO PUBLIC;


--
-- PostgreSQL database dump complete
--

